In [2]:
import numpy as np
import sys
import matplotlib.pyplot as plt
from math import ceil
from math import *
import pandas as pd
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
import random

In [19]:
X = [[2,3],[5,(-2)],[3,1]]
Y = [0.2,0,2]

X = np.array(X)
Y = np.array(Y)
mean = np.mean(X,axis=0)
std=np.std(X,axis=0,ddof=1)
X = (X-mean)/std
X = np.insert(X, 0, values = 1, axis = 1)
print(X)
thetas = np.linalg.inv(X.T@X)@X.T@Y
print(thetas)

[[ 1.         -0.87287156  0.92717265]
 [ 1.          1.09108945 -1.05962589]
 [ 1.         -0.21821789  0.13245324]]
[  0.73333333 -14.35873718 -14.09302428]
